### PR TITLE
Prepare repository rename "identity-style-guide"

### PR DESCRIPTION
**Pull request by aduth**
This updates internal code references to the GitHub repository.

Next steps:

- Rename repository in Settings
- Replace site in Cloud.gov Pages

### CODE REVIEW

**Review by zachmargolis — APPROVED** [review]
LGTM, I guess we'd want to wait until after renaming the repo to merge this? so we don't pre-break the links?

**Review by nickttng — APPROVED** [review]

**Comment by aduth** [comment]
> LGTM, I guess we'd want to wait until after renaming the repo to merge this? so we don't pre-break the links?

Yeah, thinking the correct order may be:

1. Rename the repository
2. Merge this pull request
   - Cloud.gov Pages will not rebuild because the repository doesn't exist
3. Reconfigure in Cloud.gov Pages

**Comment by zachmargolis** [comment]
> Yeah, thinking the correct order may be:

SGTM!

**Comment by aduth** [comment]
The repository is now renamed. 🎉 

But I hit a snag in migrating the Cloud.gov Pages site. 😬  I was able to create a new site, but apparently we must [reconfigure DNS to point to Cloud.gov Pages](https://cloud.gov/pages/documentation/custom-domains/#adding-a-subdomain) to be able to update site URL settings ([see related devops pull request](https://github.com/18F/identity-devops/pull/6152)).

I think it's probably fine to push forward and not revert, with the caveat that https://design.login.gov is essentially frozen in time until we can update the URL settings for the site.

**Pull request merged**
