### PR TITLE
Reset and document Prose component styles

### PR DESCRIPTION
**Pull request by aduth**
## 🛠 Summary of changes

Removes override styles for the [Prose component](https://designsystem.digital.gov/components/prose/) and adds a preview page to the internal documentation.

Related Slack discussion: https://gsa-tts.slack.com/archives/C01JVKYE4KD/p1702914619083849

Related LGDS Office Hours discussion notes: https://docs.google.com/document/d/10b7Gis_VxYT3roR01MX4hwPa6-Tq29YBaLPIB3vWnUw/edit#bookmark=id.w558e3npl6ym

Live preview URL: https://federalist-340d8801-aa16-4df5-ad22-b1e3e731098e.sites.pages.cloud.gov/preview/18f/identity-design-system/aduth-typography-prose/prose/

(Draft pending audit of effect of removing overrides)

## 👀 Screenshots

federalist-340d8801-aa16-4df5-ad22-b1e3e731098e sites pages cloud gov_preview_18f_identity-design-system_aduth-typography-prose_prose_(Computer Standard)

### CODE REVIEW

**Review by nickttng — APPROVED** [review]
The Prose styling looks good to me - Nothing that appears outstanding to flag.

Thinking about the next steps

- Create a "Prose" typography section in LGDS Figma
   - Brief guidance for "Prose" vs. default, i.e., Prose for static sites
- When this PR is approved, announce that Prose is available, and used for static sites

Anything in addition?

**Comment by aduth** [comment]
I recall we'd implemented custom styles for the brochure site since we wanted specific text styling that wasn't reflected by Prose at the time. Do we think we'd need a review step to reconcile potential changes if we were to introduce the prose style reset to the brochure site, or should we just assume that Prose is correct as-is, even if it results in some spacing deviations from the current brochure site?

As far as specifics of rolling this out, this might be one we'd consider to be a "Breaking Change" which doesn't mean whole lot in terms of potential impact, but it could be wise for us (me) to ship the [current unreleased changes](https://github.com/18F/identity-design-system/blob/36305263ab2abb1b7abe66278862db157cebb801/CHANGELOG.md#unreleased) in a minor release, so we could offer an incremental upgrade path for downstream projects. There's at least one [other breaking change I have planned (dropping support for IE11)](https://github.com/18F/identity-design-system/pull/387#issuecomment-1862826352), so it could be good timing to pair with that.

**Comment by nickttng** [comment]
> Do we think we'd need a review step to reconcile potential changes if we were to introduce the prose style reset to the brochure site, or should we just assume that Prose is correct as-is, even if it results in some spacing deviations from the current brochure site?

It'd be good to have a review step for pages with running text, like Help Center articles. Other brochure site pages can be a lightweight visual check.

For Developers and Partners, do we want to notify Team Ursula (?) that Prose is available if they want to implement it, if not already?

> There's at least one https://github.com/18F/identity-design-system/pull/387#issuecomment-1862826352, so it could be good timing to pair with that.

This sounds like a good pairing.

**Comment by aduth** [comment]
Ok, what I might do is this:

1. I publish `8.1.0` release with the current unreleased changes
2. I merge this pull request
3. I publish a _beta_ prerelease version `9.0.0-beta.1`
4. I create a pull request in [`identity-site`](https://github.com/18F/identity-site) which updates to the new version and removes all prose styling overrides
5. We collectively review the resulting preview branch to check for regressions
6. If changes are necessary in `identity-design-system`, we make and merge those changes
7. Repeat until we're comfortable that the styles are settled
8. (Somewhere in parallel to all of what's going on between step 3 and 7, I complete and merge the revival of https://github.com/18F/identity-design-system/pull/387#issuecomment-1862826352 )
9. I publish `9.0.0` final version including (1) Prose stye changes and (2) changes mentioned in https://github.com/18F/identity-design-system/pull/387#issuecomment-1862826352

>For Developers and Partners, do we want to notify Team Ursula (?) that Prose is available if they want to implement it, if not already?

I think a review process using beta releases like described in the list above would make sense for the developer site, sure 👍 I might take that on myself to initiate and coordinate review with the partnerships teams.

**Comment by nickttng** [comment]
Smells like a plan! 👃🏼

**Comment by aduth** [comment]
Visual regression failures are expected since (1) there's a new sidebar navigation link for Prose documentation and (2) the internal documentation site itself uses Prose, which would be affected by these styling changes.

**Comment by aduth** [comment]
>4. I create a pull request in [`identity-site`](https://github.com/18F/identity-site) which updates to the new version and removes all prose styling overrides

All steps up to this are complete, and the preview pull request is at https://github.com/18F/identity-site/pull/1207

**Pull request merged**
